### ISSUE TITLE
Bad request response

### ISSUE THREAD

**Issue by chiloanemike** [camaraproject/QualityOnDemand_PI1#3]
I have been trying to create a session and I am always getting a bad request error message. I also tried with the swagger and it still gives me the same error message. Is there anything I'm missing out? 
Here is my request json body:

`{
    "duration": "50",
    "ueId": {
        "externalId": "123456789@domain.com",
        "msisdn": "123456789",
        "ipv4addr": "192.168.0.0/24"
    },
    "asId": {
        "ipv4addr": "192.168.0.0/24"
    },
    "uePorts": {
        "ranges": [
            {
                "from": 5010,
                "to": 5020
            }
        ],
        "ports": [
            5060,
            5070
        ]
    },
    "asPorts": {
        "ranges": [
            {
                "from": 5010,
                "to": 5020
            }
        ],
        "ports": [
            5060,
            5070
        ]
    },
    "qos": "QOS_E",
}`

**Comment by hdamker** [comment]
@chiloanemike as your question is answered, would you like to close the issue?
