### ISSUE TITLE
Facing Issue in  AsSessionWithQoSApiSubscriptionLevelPostOperationApi while implementing 

### ISSUE THREAD

**Issue by SanketKulkarni6413** [camaraproject/QualityOnDemand_PI1#4]
I am executing QualityOnDemand_PI1 locally on Computed URL:http://localhost:9091/qod/v0.
While running post request I am facing error in AsSessionWithQoSApiSubscriptionLevelPostOperationApi this class in package com.camara.scef.api 
Error is at return apiClient.invokeAPI("/{scsAsId}/subscriptions", HttpMethod.POST, uriVariables, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAccept, localVarContentType, localVarAuthNames, localReturnType); this line. 
In controller for post request there is createSession method. But for this AsSessionWithQoSApiSubscriptionLevelPostOperationApi there is no such implementation provided. 
Can you help me to figure it out.

**Comment by SanketKulkarni6413** [comment]
Hi @maxl2287 can help me to solve this issue.

**Comment by maxl2287** [comment]
Can you please add your logs please?

**Comment by SanketKulkarni6413** [comment]
[.log](https://github.com/camaraproject/QualityOnDemand_PI1/files/11767517/default.log)

**Comment by SanketKulkarni6413** [comment]
Hi @maxl2287 I have attached log file.

**Comment by maxl2287** [comment]
I am currently not able to review this, because I am out of office.

I forwarded this issue to other related devs.

**Comment by akoshunyadi** [comment]
As I understand this is runtime problem at apiClient.invokeAPI("/{scsAsId}/subscriptions", which means the API call to the backend, which should be a 3GPP NEF endpoint. Is that endpoint reachable?
